name: monitor


on:
  
  # push: # push触发
  #   branches: [ main ]
  watch:
    types: [started]
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: ' 0 * * *  ?' # cron表达式，Actions时区是UTC时间，所以要往前推8个小时(6-23)
    

jobs:
  monitor:
    if: github.event.repository.owner.id == github.event.sender.id
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]
        node-registry: ['https://registry.npmjs.org']

    steps:
    
    # 检出
    - name: Checkout
      uses: actions/checkout@v2
      
    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: ${{ matrix.node-registry }}

    - name: Install dependencies
      run: npm install
       
    - name: Run Monitor
      env:
          wxkey: ${{secrets.wxkey}}
      run: node src/index.js --wxkey=${wxkey}
